# -*- coding: utf-8 -*-
"""Q1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eri8l_9h-KxU3iAxIZmw1NaAlPd_WHtF
"""

#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 23 13:20:15 2019

@author: chin-weihuang
"""


from __future__ import print_function
import numpy as np
import torch 
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import torch.nn.functional as F
import samplers
import jsloss
from jsloss import Discriminator as Discriminator
from jsloss import JSD as JSD
from wgan_gp_code import Critic, WGAN_GPloss

#Question 1.3
output_list = []
epoch_count_js = 500
epoch_count_wgan = 12000

#loop over the values between -1 and 1 for (phi, U(0,1))
for phi in np.linspace(-1,1,21):
  jsd = JSD(x_val=phi, minibatch_size=512, epoch_count=epoch_count_js, learning_rate=1e-3, \
      input_size=2, hidden_size=10, output_size=1,  \
      real_sampler = samplers.distribution1, \
      fake_sampler = samplers.distribution1  \
      )
  output_list.append(jsd)
  
  
wgan_output_list = []
losses = []
for phi in np.linspace(-1,1,21):
  wgan_gp = WGAN_GPloss(x_val=phi, minibatch_size=512, epoch_count=epoch_count_wgan, learning_rate=1e-3, losses = losses,\
      input_size=2, hidden_size=10, output_size=1,  \
      real_sampler = samplers.distribution1, \
      fake_sampler = samplers.distribution1  \
      )
  wgan_output_list.append(wgan_gp)

torch.stack(output_list)
plt.figure()
plt.scatter(np.linspace(-1,1,21), \
            torch.stack(output_list).cpu().detach().numpy(), label = "Jensen-Shannon Divergence")

plt.scatter(np.linspace(-1,1,21), \
            torch.stack(wgan_output_list).cpu().detach().numpy(), label = "WGAN_GP distance")

plt.xlabel('Values of $\phi \in [-1,1]$ with intervals of 0.1 ' )
plt.ylabel('JS Divergence')
plt.title('Jensen Shanon divergence between (0,U[0,1]) and ($\phi$,U[0,1])')
plt.legend()
plt.show()

"""The Jensen-Shannon Divergence at $ \phi = 0$ is 0 (overlayed with WGAN_GP distance)"""